In [5]:
import folium
import pandas as pd
import numpy as np

In [7]:
LON = pd.Series(np.random.randint(1,20,size=1000))
LAT = pd.Series(np.random.randint(56,60,size=1000))
LON.name = 'LON'
LAT.name = 'LAT'

df= pd.concat([LON,LAT], axis=1)
df

     LON  LAT
0      8   56
1      5   57
2      1   57
3     14   57
4      2   58
5      4   59
6     11   58
7     16   58
8      7   59
9     17   58
10    15   58
11    10   57
12    17   59
13    15   56
14    16   56
15    10   59
16    14   58
17    12   57
18     2   56
19     4   56
20    12   56
21     5   59
22    12   56
23    16   57
24    17   57
25     9   57
26     6   57
27     7   56
28    12   56
29     5   59
..   ...  ...
970    9   56
971   15   56
972    7   56
973   14   58
974    1   59
975   16   58
976    1   56
977    9   58
978    3   59
979    8   58
980   16   57
981    4   57
982   13   58
983   12   59
984    3   58
985   12   58
986   17   56
987   15   57
988    8   58
989   10   58
990   13   58
991   15   56
992   14   57
993   16   56
994   15   56
995    9   58
996   10   58
997    9   57
998    4   58
999   15   59

[1000 rows x 2 columns]

In [3]:
map=folium.Map(location=[df['LAT'].mean(),df['LON'].mean()],zoom_start=6,tiles='Mapbox bright')

fg=folium.FeatureGroup(name="Volcano Locations")
for lat,lon in zip(df['LAT'],df['LON']):
    fg.add_child(folium.Marker(location=[lat,lon],icon=folium.Icon(color='red')))

mg=folium.FeatureGroup(name="Volcano Locations")
for lat,lon in zip(df['LAT']+2,df['LON']+2):
    mg.add_child(folium.Marker(location=[lat,lon],icon=folium.Icon(color='green')))    
    
map.add_child(fg)
map.add_child(mg)

map.save(outfile='map.html')